inherit_gem:
  rubocop-rails-omakase: rubocop.yml

require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  NewCops: enable
  DisabledByDefault: false
  TargetRubyVersion: 3.3
  Exclude:
    - db/schema.rb
    - db/migrate/*
    - bin/*

Bundler/OrderedGems:
  Enabled: true
Layout/ClassStructure:
  Enabled: true
Layout/EmptyLineAfterGuardClause:
  Enabled: true
Layout/EmptyLines:
  Enabled: true
Layout/IndentationConsistency:
  Enabled: true
  EnforcedStyle: normal
Layout/IndentationWidth:
  Enabled: true
Layout/LineLength:
  Enabled: false
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Layout/SpaceInsideArrayLiteralBrackets:
  EnforcedStyle: no_space
Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
Layout/SpaceInsidePercentLiteralDelimiters:
  Enabled: true
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Minitest/AssertPredicate:
  Enabled: false
Minitest/EmptyLineBeforeAssertionMethods:
  Enabled: false
Minitest/MultipleAssertions:
  Enabled: false
Naming/AccessorMethodName:
  Enabled: false
Performance:
  Enabled: true
Rails:
  Enabled: true
Rails/I18nLocaleTexts:
  Enabled: false
Style/Alias:
  EnforcedStyle: prefer_alias_method
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  EnforcedStyle: never
Style/HashSyntax:
  EnforcedShorthandSyntax: always
  EnforcedStyle: ruby19
Style/IfUnlessModifier:
  Enabled: true
Style/NumericLiterals:
  Enabled: false
Style/Send:
  Enabled: true
Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
Style/SymbolArray:
  Enabled: true
Style/WordArray:
  Enabled: true
