global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["127.0.0.1:9090"]

  - job_name: node_exporter
    static_configs:
      - targets: ["10.0.0.50:9100"]
      - targets: ["10.0.0.10:9100"]

  - job_name: cadvisor
    static_configs:
      - targets: ["10.0.0.50:9200"]
      - targets: ["10.0.0.10:9200"]
