# Name of your application. Used to uniquely configure containers.
service: visualizer

# Name of the container image.
image: mrfoto/visualizer

# Deploy to these servers.
servers:
  web:
    hosts:
      - 78.47.79.8
  job:
    hosts:
      - 78.47.79.8
    cmd: bin/sidekiq

registry:
  username: mrfoto
  password:
    - MRSK_REGISTRY_PASSWORD

env:
  clear:
    REDIS_URL: "redis://5.75.162.200:6379/0"
    CACHE_REDIS_URL: "redis://5.75.162.200:6380/0"
  secret:
    - RAILS_MASTER_KEY
    - DATABASE_URL

builder:
  multiarch: false

accessories:
  db:
    image: postgres:15
    hosts:
      - 5.75.162.200
    port: 5432:5432
    env:
      clear:
        POSTGRES_DB: visualizer
      secret:
        - POSTGRES_USER
        - POSTGRES_PASSWORD
    command:
      - "postgres"
      - "-c"
      - "max_connections=200"
      - "-c"
      - "shared_buffers=1GB"
      - "-c"
      - "effective_cache_size=3GB"
      - "-c"
      - "work_mem=2621kB"
      - "-c"
      - "maintenance_work_mem=256MB"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "checkpoint_completion_target=0.9"
      - "-c"
      - "wal_buffers=16MB"
      - "-c"
      - "default_statistics_target=100"
      - "-c"
      - "effective_io_concurrency=200"
      - "-c"
      - "min_wal_size=1GB"
      - "-c"
      - "max_wal_size=4GB"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.track=all"
    volumes:
      - /data/postgres:/var/lib/postgresql/data

  redis-main:
    image: redis:7.0
    hosts:
      - 5.75.162.200
    port: 6379:6379
    volumes:
      - /data/redis/main:/data
  redis-cache:
    image: redis:7.0
    hosts:
      - 5.75.162.200
    port: 6380:6379
    volumes:
      - /data/redis/cache:/data
