# Name of your application. Used to uniquely configure containers.
service: visualizer

# Name of the container image.
image: mrfoto/visualizer

# Deploy to these servers.
servers:
  web:
    hosts:
      - 88.99.170.153
    options:
      add-host: host.docker.internal:host-gateway
  job:
    hosts:
      - 88.99.170.153
    cmd: bin/sidekiq
    options:
      add-host: host.docker.internal:host-gateway

registry:
  username: mrfoto
  password:
    - MRSK_REGISTRY_PASSWORD

env:
  clear:
    DATABASE_URL: "postgres://postgres@host.docker.internal:5432/visualizer"
    REDIS_URL: "redis://host.docker.internal:6379/0"
    CACHE_REDIS_URL: "redis://host.docker.internal:6380/0"
  secret:
    - RAILS_MASTER_KEY

builder:
  multiarch: false

accessories:
  db:
    image: "postgres:15"
    hosts:
      - 88.99.170.153
    port: "172.17.0.1:5432:5432"
    env:
      clear:
        POSTGRES_HOST_AUTH_METHOD: trust
        POSTGRES_DB: visualizer
  redis:
    image: redis:7.0
    hosts:
      - 88.99.170.153
    port: "172.17.0.1:6379:6379"
  cache-redis:
    image: redis:7.0
    hosts:
      - 88.99.170.153
    port: "172.17.0.1:6380:6380"
