name: Main Branch

on:
  push:
    branches: [main]

jobs:
  call-ruby-tests:
    name: Ruby Tests
    uses: ./.github/workflows/ruby-tests.yml
    secrets: inherit
  call-kamal:
    name: Kamal
    needs: call-ruby-tests
    uses: ./.github/workflows/kamal.yml
    secrets: inherit
