name: Ruby Tests
on: workflow_call
permissions:
  contents: read
jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Start system dependency installation
        run: |
          sudo systemd-run --unit=install-ci-dependencies --no-block \
            --property=Type=oneshot --property=RemainAfterExit=yes \
            /bin/bash -e -c 'apt-get update && apt-get install --no-install-recommends -y libvips'

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 4.0.6
          bundler-cache: true

      - name: Wait for system dependency installation
        run: |
          sudo systemctl start install-ci-dependencies.service
          sudo journalctl --unit=install-ci-dependencies --no-pager

      - name: Scan for common Rails security vulnerabilities using static analysis
        run: bin/brakeman --no-pager

      - name: Scan for security vulnerabilities in JavaScript dependencies
        run: bin/importmap audit

      - name: Lint code for consistent style
        run: bin/rubocop -f github

  unit_tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    env:
      PGHOST: 127.0.0.1
      PGUSER: postgres
      PGPASSWORD: postgres
      PGPORT: 5432
      RAILS_ENV: test

    services:
      postgres:
        image: postgres:18
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v6

      - name: Start system dependency installation
        run: |
          sudo systemd-run --unit=install-ci-dependencies --no-block \
            --property=Type=oneshot --property=RemainAfterExit=yes \
            /bin/bash -e -c 'apt-get update && apt-get install --no-install-recommends -y libpq-dev libvips'

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 4.0.6
          bundler-cache: true

      - name: Wait for system dependency installation
        run: |
          sudo systemctl start install-ci-dependencies.service
          sudo journalctl --unit=install-ci-dependencies --no-pager

      - name: Setup database
        run: bin/rails db:test:prepare

      - name: Run unit tests
        run: bin/rails test
